### PR TITLE
cvs download: apply template

### PR DESCRIPTION
**Pull request by mrsmuneton**
@davidguttman thought that it might be nice in general if the formatting template could be taken into account in the csv

### CODE REVIEW

**Comment by davidguttman** [comment]
This should be in an option flag. Templates are decoration around the
underlying data. If the template is applied before the export, underlying
data is lost/mangled (precision lost, extra non-number characters added,
etc...).

**Comment by mrsmuneton** [comment]
Perfect I will make it a flag and update this, that makes total sense =)

**Comment by mrsmuneton** [comment]
@davidguttman I added the option flag `csvTemplateFormat` if that name sounds good.  I also could (either in this PR or another) add a section to the readme to describe the optional params.

**Comment by davidguttman** [comment]
Yep, that would be great.

**Comment by mrsmuneton** [comment]
@davidguttman added a list of those optional arguments, you can see how it looks at
https://github.com/mrsmuneton/react-pivot/tree/csv-apply-template

:)

**Comment by davidguttman** [comment]
Awesome! 💯

**Pull request merged**
