### PR TITLE
Add 'node_modules' to .gitignore + Create nvm file. PR#1

### PR DESCRIPTION
**Pull request by marcjal**

### CODE REVIEW

**Comment by Arshavin86** [comment]
Do we actually need Node 12? And if so, is this the best way to specify that (as opposed to the engines field in package.json). That should probably go in some PR.

**Comment by marcjal** [comment]
> Do we actually need Node 12? And if so, is this the best way to specify that (as opposed to the engines field in package.json). That should probably go in some PR.

Hi @Arshavin86 I  can add  also  the configuration in package.json  but the .nvmrc  is a interesting solution because you can choose  automatically to that version with the command `nvm use` and the last information that I read was the version `lts/carbon -> v8.16.2` is going to be outdated and the last LTS is `lts/erbium -> v12.13.0` so I thought that this version is the suitable version to work from now on.

**Comment by Arshavin86** [comment]
Got it! I prefer not to force people to use a version manager.

**Comment by marcjal** [comment]
> Got it! I prefer not to force people to use a version manager.

@Arshavin86 I'm curious now because I upgrade the packages with that node version, do you think maybe with another node version another package version is installed it?

**Pull request closed without merging**
