### PR TITLE
Require individual lodash functions.

### LINKED ISSUE #35: reduced bundle size
hello!

i see a some `requires` where `lodash` is required in as full.  [ref](https://github.com/davidguttman/react-pivot/blob/master/lib/column-control.jsx#L1)

if instead a `require('lodash/someFun')` is used, the bundler of choice (webpack/browserify) won't need to included the full library.

easy kbs worth saving!

thanks for the lib

### PR DESCRIPTION
**Pull request by mrsmuneton**
To save kbs for a smaller footprint, only include lodash functions that are required.
Closes #35.

### CODE REVIEW

**Comment by davidguttman** [comment]
Having issues getting `npm run example` to work. Think we need a newer version of `lodash`.

**Comment by mrsmuneton** [comment]
@davidguttman npm run example looks to be running now.
I also got an error that said i should be using a new version of react so i upgraded that too... let me know if that seems not okay in anyway

**Comment by davidguttman** [comment]
If `npm run example` worked without upgrading React, it should probably go in its own PR.

**Comment by mrsmuneton** [comment]
@davidguttman pulled the react upgrade out of this and will open another PR for that =)

**Comment by davidguttman** [comment]
💯

**Comment by davidguttman** [comment]
In `v1.15.0`

**Pull request merged**
