### PR TITLE
Add support for custom onSort function in calculations/dimensions

### PR DESCRIPTION
**Pull request by JosueDevMark**
Support a custom `onSort` function for calculations or dimensions

### CODE REVIEW

**Comment by davidguttman** [comment]
@JosueDevMark thanks for the PR, looks like a useful feature. Let's change the name from `onSort()` to `sortBy()` and I'll merge it.

**Comment by JosueDevMark** [comment]
@davidguttman I have just change it

**Comment by JosueDevMark** [comment]
Thanks @davidguttman! so when will be available on npm?

**Comment by davidguttman** [comment]
it's in `3.1.0`

**Pull request merged**
